#!/usr/bin/env bash

GAME_ROOT_DIR="$(dirname -- "${BASH_SOURCE[0]}" | xargs realpath)"
export WINEPREFIX="${GAME_ROOT_DIR}/wineprefix"
export WINEARCH=win64
export vblank_mode=0
export WINEDLLOVERRIDES=winemenubuilder.exe=d#
export WINEESYNC=1
export WINEFSYNC=1
export DXVK_ASYNC=1
export DXVK_STATE_CACHE_PATH="$WINEPREFIX"
export DXVK_CONFIG_FILE="$WINEPREFIX/dxvk.conf"
export WINE_FULLSCREEN_FSR=1
